Repository GuanceCloud/cliutils, pull requests merged in 2023-12, with the labels that each got.

#65 Fix httpErr weakness
  network/http/err.go
  network/http/err_test.go
Labels: size/L

#63 specify capacity when creating kvs and tags
  point/kvs.go
Labels: size/S

#67 update Pipeline functions document
  pipeline/ptinput/funcs/md/agg_create.en.md
  pipeline/ptinput/funcs/md/agg_create.md
  pipeline/ptinput/funcs/md/agg_metric.en.md
  pipeline/ptinput/funcs/md/agg_metric.md
  pipeline/ptinput/funcs/md/create_point.en.md
  pipeline/ptinput/funcs/md/create_point.md
  pipeline/ptinput/funcs/md/mquery_refer_table.en.md
  pipeline/ptinput/funcs/md/mquery_refer_table.md
  pipeline/ptinput/funcs/md/query_refer_table.en.md
  pipeline/ptinput/funcs/md/query_refer_table.md
Labels: size/M
