Repository GuanceCloud/cliutils, pull requests merged in 2023-11, with the labels that each got.

#53 fix: fix hang on bad datafile
  diskcache/drop.go
  diskcache/drop_test.go
  diskcache/get.go
  diskcache/get_test.go
  diskcache/metric.go
  diskcache/put_test.go
  diskcache/rotate.go
  diskcache/switch.go
Labels: size/L

#54 test: add test case for json tag in line protocol
  point/lp_test.go
Labels: size/M

#52 cors-multi-origin-support
  network/http/gin.go
  network/http/gin_test.go
Labels: size/L

#56 fix ut errors
  diskcache/get_test.go
  network/http/gin_test.go
  point/lp_test.go
Labels: size/S

#55 fix(dialtesting): fix icmp checking for response time
  dialtesting/icmp.go
Labels: size/XS

#51 feat(dialtesting): add tcp dial test for response message
  dialtesting/http.go
  dialtesting/success.go
  dialtesting/tcp.go
  dialtesting/tcp_test.go
Labels: size/L

#40 fix(dialtesting): fix dialtesting http unit test
  dialtesting/http_test.go
Labels: size/XL

#58 feat: Supports log printing of tracing information
  logger/logger_ctx.go
  logger/logger_test.go
  logger/opt.go
Labels: size/L

#59 fix: fix diskcache empty pos
  diskcache/open_test.go
  diskcache/pos.go
  diskcache/switch.go
Labels: size/M

#60 Fix unexpected removing rotate file
  diskcache/get_test.go
  diskcache/rotate.go
Labels: size/M
