Repository GuanceCloud/cliutils, pull requests merged in 2023-10, with the labels that each got.

#37 feat: use cron
  go.mod
  go.sum
  logger/root.go
  vendor/github.com/robfig/cron/v3/.gitignore
  vendor/github.com/robfig/cron/v3/.travis.yml
  vendor/github.com/robfig/cron/v3/LICENSE
  vendor/github.com/robfig/cron/v3/README.md
  vendor/github.com/robfig/cron/v3/chain.go
  vendor/github.com/robfig/cron/v3/constantdelay.go
  vendor/github.com/robfig/cron/v3/cron.go
  vendor/github.com/robfig/cron/v3/doc.go
  vendor/github.com/robfig/cron/v3/logger.go
  vendor/github.com/robfig/cron/v3/option.go
  vendor/github.com/robfig/cron/v3/parser.go
  vendor/github.com/robfig/cron/v3/spec.go
  vendor/modules.txt
Labels: size/XXL

#38 Create go.yml
  .github/workflows/go.yml
  Makefile
Labels: size/M

#42 Update encoding naming
  filter/lex.go
  metrics/http.go
  metrics/point.go
  point/encode.go
Labels: size/M

#45 feat: add pipeline function `pt_name`
  network/ws/epoll_linux.go
  pipeline/ptinput/funcs/all.go
  pipeline/ptinput/funcs/all_doc.go
  pipeline/ptinput/funcs/all_doc_en.go
  pipeline/ptinput/funcs/fn_pt_name.go
  pipeline/ptinput/funcs/fn_pt_name_test.go
  pipeline/ptinput/funcs/fn_set_measurement.go
  pipeline/ptinput/funcs/md/pt_name.en.md
  pipeline/ptinput/funcs/md/pt_name.md
  pipeline/ptinput/funcs/utils.go
Labels: size/L, lgtm

#50 fix: fix diskcache fallback error handling
  diskcache/get.go
  diskcache/get_test.go
  diskcache/metric.go
  point/sort.go
Labels: size/M
