Repository GuanceCloud/cliutils, pull requests merged in 2024-04, with the labels that each got.

#84 feat(dialtesting): add hostname method
  dialtesting/http.go
  dialtesting/icmp.go
  dialtesting/task.go
  dialtesting/tcp.go
  dialtesting/websocket.go
Labels: size/S

#79 refact decode
  Makefile
  go.mod
  go.sum
  network/http/err.go
  point/any.go
  point/any_test.go
  point/check.go
  point/check_test.go
  point/decode.go
  point/decode_test.go
  point/encode_test.go
  point/equal.go
  point/err.go
  point/init.go
  point/json.go
  point/json_test.go
  point/kvs.go
  point/kvs_test.go
  point/lp.go
  point/lp_test.go
  point/new_point_test.go
  point/point.pb.go
  point/point.proto
  point/point_test.go
  point/specs.go
  vendor/github.com/influxdata/influxdb1-client/models/inline_fnv.go
  vendor/github.com/influxdata/influxdb1-client/models/points.go
  vendor/github.com/influxdata/influxdb1-client/models/time.go
  vendor/github.com/influxdata/influxdb1-client/v2/client.go
  vendor/github.com/influxdata/influxdb1-client/v2/udp.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
Labels: size/XXL

#87 Revert "refact decode (#79)"
  Makefile
  go.mod
  go.sum
  network/http/err.go
  point/any.go
  point/any_test.go
  point/check.go
  point/check_test.go
  point/decode.go
  point/decode_test.go
  point/encode_test.go
  point/equal.go
  point/err.go
  point/init.go
  point/json.go
  point/json_test.go
  point/kvs.go
  point/kvs_test.go
  point/lp.go
  point/lp_test.go
  point/new_point_test.go
  point/point.pb.go
  point/point.proto
  point/point_test.go
  point/specs.go
  vendor/github.com/influxdata/influxdb1-client/models/inline_fnv.go
  vendor/github.com/influxdata/influxdb1-client/models/points.go
  vendor/github.com/influxdata/influxdb1-client/models/time.go
  vendor/github.com/influxdata/influxdb1-client/v2/client.go
  vendor/github.com/influxdata/influxdb1-client/v2/udp.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
Labels: size/XXL

#81 add http request func and cache module
  pipeline/manager/script.go
  pipeline/manager/scriptstore.go
  pipeline/ptinput/funcs/all.go
  pipeline/ptinput/funcs/all_doc.go
  pipeline/ptinput/funcs/all_doc_en.go
  pipeline/ptinput/funcs/fn_cache.go
  pipeline/ptinput/funcs/fn_cache_test.go
  pipeline/ptinput/funcs/fn_http_request.go
  pipeline/ptinput/funcs/fn_http_request_test.go
  pipeline/ptinput/funcs/md/cache_get.en.md
  pipeline/ptinput/funcs/md/cache_get.md
  pipeline/ptinput/funcs/md/cache_set.en.md
  pipeline/ptinput/funcs/md/cache_set.md
  pipeline/ptinput/funcs/md/http_request.en.md
  pipeline/ptinput/funcs/md/http_request.md
  pipeline/ptinput/plcache/cache.go
  pipeline/ptinput/plcache/cache_test.go
  pipeline/ptinput/point.go
Labels: size/XL, lgtm

#89 fix: fix FromJSONPoint bug
  point/json_test.go
  point/point.go
Labels: size/M

#91 iss 2167 add gjson func
  pipeline/ptinput/funcs/all.go
  pipeline/ptinput/funcs/all_doc.go
  pipeline/ptinput/funcs/all_doc_en.go
  pipeline/ptinput/funcs/fn_gjson.go
  pipeline/ptinput/funcs/fn_gjson_test.go
  pipeline/ptinput/funcs/md/gjson.en.md
  pipeline/ptinput/funcs/md/gjson.md
Labels: size/L
