Repository GuanceCloud/cliutils, pull requests merged in 2024-05, with the labels that each got.

#90 Lp parse error
  Makefile
  go.mod
  go.sum
  network/http/err.go
  point/any_test.go
  point/check.go
  point/check_test.go
  point/decode.go
  point/decode_test.go
  point/easyproto_test.go
  point/encode_test.go
  point/equal.go
  point/err.go
  point/init.go
  point/json.go
  point/json_test.go
  point/kvs.go
  point/kvs_test.go
  point/lp.go
  point/lp_test.go
  point/new_point_test.go
  point/point.go
  point/point.proto
  point/point_test.go
  point/ptpool.go
  point/ptpool_test.go
  point/rand_test.go
  point/val.go
  vendor/github.com/influxdata/influxdb1-client/models/inline_fnv.go
  vendor/github.com/influxdata/influxdb1-client/models/points.go
  vendor/github.com/influxdata/influxdb1-client/models/time.go
  vendor/github.com/influxdata/influxdb1-client/v2/client.go
  vendor/github.com/influxdata/influxdb1-client/v2/udp.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
Labels: size/XXL

#97 add dynamic precison detect
  go.mod
  go.sum
  point/decode.go
  point/decode_test.go
  point/enc.go
  point/encode.go
  point/encode_v2.go
  point/lp.go
  point/option.go
  vendor/github.com/influxdata/influxdb1-client/models/points.go
  vendor/modules.txt
Labels: size/XL

#93 feat: add +inf/-inf float support
  point/check.go
  point/decode.go
  point/decode_test.go
  point/encode_test.go
  point/err.go
Labels: size/L

#95 point window
  pipeline/manager/script.go
  pipeline/manager/scriptstore.go
  pipeline/ptinput/funcs/all.go
  pipeline/ptinput/funcs/all_doc.go
  pipeline/ptinput/funcs/all_doc_en.go
  pipeline/ptinput/funcs/fn_pt_window.go
  pipeline/ptinput/funcs/fn_pt_window_test.go
  pipeline/ptinput/funcs/md/point_window.en.md
  pipeline/ptinput/funcs/md/point_window.md
  pipeline/ptinput/funcs/md/window_hit.en.md
  pipeline/ptinput/funcs/md/window_hit.md
  pipeline/ptinput/point.go
  pipeline/ptinput/ptwindow/pool.go
  pipeline/ptinput/ptwindow/pt_window.go
  point/ptpool.go
Labels: enhancement, size/XL

#98 fix line-proto parse time precison
  point/lp.go
Labels: size/XS

#99 fix(point): add current time when point time is zero
  point/decode.go
  point/json.go
Labels: size/S
