Repository GuanceCloud/cliutils, pull requests merged in 2024-09, with the labels that each got.

#115 Add copyright declaration and package comments
  pprofparser/cfg/cfg.go
  pprofparser/cfg/cfg_test.go
  pprofparser/domain/events/type.go
  pprofparser/domain/languages/lang.go
  pprofparser/domain/parameter/parameter.go
  pprofparser/domain/pprof/frame.go
  pprofparser/domain/pprof/summary.go
  pprofparser/domain/quantity/kind.go
  pprofparser/domain/quantity/quantity.go
  pprofparser/domain/quantity/quantity_test.go
  pprofparser/domain/quantity/unit.go
  pprofparser/domain/tracing/tracing.go
  pprofparser/service/parsing/aggregators.go
  pprofparser/service/parsing/aggregators_test.go
  pprofparser/service/parsing/collapse.go
  pprofparser/service/parsing/collapse_test.go
  pprofparser/service/parsing/display.go
  pprofparser/service/parsing/metadata.go
  pprofparser/service/parsing/metadata_test.go
  pprofparser/service/parsing/parser.go
  pprofparser/service/parsing/pprof.go
  pprofparser/service/parsing/pprof_test.go
  pprofparser/service/parsing/sampletype.go
  pprofparser/service/parsing/sampletype_test.go
  pprofparser/service/storage/disk.go
  pprofparser/service/storage/oss.go
  pprofparser/service/storage/storage.go
  pprofparser/tools/filepathtoolkit/format.go
  pprofparser/tools/filepathtoolkit/format_test.go
  pprofparser/tools/filepathtoolkit/stat.go
  pprofparser/tools/filepathtoolkit/stat_test.go
  pprofparser/tools/jsontoolkit/cast.go
  pprofparser/tools/jsontoolkit/json.go
  pprofparser/tools/logtoolkit/logger.go
  pprofparser/tools/mathtoolkit/math.go
  pprofparser/tools/mathtoolkit/math_test.go
  pprofparser/tools/parsetoolkit/pprof.go
  pprofparser/tools/parsetoolkit/pprof_test.go
Labels: size/L

#114 fix(dialtesting): add task field `df_label`
  dialtesting/http.go
  dialtesting/icmp.go
  dialtesting/task.go
  dialtesting/tcp.go
  dialtesting/websocket.go
Labels: size/M

#118 Bug fix: Incorrect recycling of objects in Pipeline point window
  pipeline/ptinput/ptwindow/pt_window.go
Labels: size/S
