Repository GuanceCloud/cliutils, pull requests merged in 2024-12, with the labels that each got.

#125 Fix the performance degradation issue of `valid_json` function
  pipeline/ptinput/funcs/fn_valid_json.go
  pipeline/ptinput/funcs/md/parse_int.en.md
  pipeline/ptinput/funcs/md/parse_int.md
Labels: size/XS

#128 Fix concurrency issues caused by Pipeline `cache` function
  pipeline/ptinput/plcache/cache.go
  pipeline/ptinput/plcache/cache_test.go
Labels: size/M

#130 test: add gzip test on shuffled kvs
  go.mod
  go.sum
  point/kvs.go
  point/kvs_test.go
  vendor/github.com/klauspost/compress/LICENSE
  vendor/github.com/klauspost/compress/flate/deflate.go
  vendor/github.com/klauspost/compress/flate/dict_decoder.go
  vendor/github.com/klauspost/compress/flate/fast_encoder.go
  vendor/github.com/klauspost/compress/flate/huffman_bit_writer.go
  vendor/github.com/klauspost/compress/flate/huffman_code.go
  vendor/github.com/klauspost/compress/flate/huffman_sortByFreq.go
  vendor/github.com/klauspost/compress/flate/huffman_sortByLiteral.go
  vendor/github.com/klauspost/compress/flate/inflate.go
  vendor/github.com/klauspost/compress/flate/inflate_gen.go
  vendor/github.com/klauspost/compress/flate/level1.go
  vendor/github.com/klauspost/compress/flate/level2.go
  vendor/github.com/klauspost/compress/flate/level3.go
  vendor/github.com/klauspost/compress/flate/level4.go
  vendor/github.com/klauspost/compress/flate/level5.go
  vendor/github.com/klauspost/compress/flate/level6.go
  vendor/github.com/klauspost/compress/flate/regmask_amd64.go
  vendor/github.com/klauspost/compress/flate/regmask_other.go
  vendor/github.com/klauspost/compress/flate/stateless.go
  vendor/github.com/klauspost/compress/flate/token.go
  vendor/github.com/klauspost/compress/gzip/gunzip.go
  vendor/github.com/klauspost/compress/gzip/gzip.go
  vendor/modules.txt
Labels: size/XXL

#131 Add parallel test on ptpool
  point/ptpool.go
  point/ptpool_test.go
Labels: size/L

#127 Restricting network access to http_request functions
  pipeline/ptinput/funcs/fn_http_request.go
  pipeline/ptinput/funcs/fn_http_request_test.go
Labels: size/L
