Repository GuanceCloud/cliutils, pull requests merged in 2025-02, with the labels that each got.

#135 Pipeline adds pl_settings function
  pipeline/manager/script.go
  pipeline/ptinput/funcs/all.go
  pipeline/ptinput/funcs/all_doc.go
  pipeline/ptinput/funcs/all_doc_en.go
  pipeline/ptinput/funcs/fn_setopt.go
  pipeline/ptinput/funcs/fn_setopt_test.go
  pipeline/ptinput/funcs/md/setopt.en.md
  pipeline/ptinput/funcs/md/setopt.md
  pipeline/ptinput/point.go
  pipeline/ptinput/pt.go
Labels: size/L

#136 feat(dialtesting): add multi type of task
  dialtesting/http.go
  dialtesting/http_script.go
  dialtesting/http_script_test.go
  dialtesting/http_test.go
  dialtesting/icmp.go
  dialtesting/icmp_test.go
  dialtesting/multi.go
  dialtesting/multi_test.go
  dialtesting/task.go
  dialtesting/tcp.go
  dialtesting/tcp_test.go
  dialtesting/websocket.go
  dialtesting/websocket_test.go
Labels: size/XXL

#137 add object_change category
  point/category.go
Labels: size/XS
