Repository GuanceCloud/cliutils, pull requests merged in 2025-03, with the labels that each got.

#139 fix Pipeline memory leak
  dialtesting/http_script.go
  go.mod
  go.sum
  vendor/github.com/GuanceCloud/pipeline-go/LICENSE
  vendor/github.com/GuanceCloud/pipeline-go/constants/constants.go
  vendor/github.com/GuanceCloud/pipeline-go/lang/log_status.go
  vendor/github.com/GuanceCloud/pipeline-go/lang/options.go
  vendor/github.com/GuanceCloud/pipeline-go/lang/platypus/script.go
  vendor/github.com/GuanceCloud/pipeline-go/manager/manager.go
  vendor/github.com/GuanceCloud/pipeline-go/manager/name_rule.go
  vendor/github.com/GuanceCloud/pipeline-go/manager/patterns.go
  vendor/github.com/GuanceCloud/pipeline-go/manager/relation.go
  vendor/github.com/GuanceCloud/pipeline-go/manager/script.go
  vendor/github.com/GuanceCloud/pipeline-go/manager/scriptstore.go
  vendor/github.com/GuanceCloud/pipeline-go/ptinput/plmap/aggmap.go
  vendor/modules.txt
Labels: size/XXL

#140 fix error message
  dialtesting/multi.go
Labels: size/XS

#141 limit error message length
  dialtesting/http.go
  dialtesting/http_script.go
Labels: size/S
