Repository GuanceCloud/cliutils, pull requests merged in 2025-04, with the labels that each got.

#144 Add category object change
  point/category.go
Labels: size/XS

#145 feat: add new option to disable drop-data when diskcache full
  diskcache/diskcache.go
  diskcache/options.go
  diskcache/put.go
Labels: size/S

#143 chore: add more error details
  diskcache/get.go
  diskcache/pos.go
  diskcache/rotate.go
  diskcache/switch.go
Labels: size/S

#147 Http option
  network/http/gin.go
Labels: size/XS

#146 chore: set default logging point status from `unknown` to `info`
  point/decode_test.go
  point/new_point_test.go
  point/point_test.go
  point/specs.go
Labels: size/S

#148 Set default log point level
  .golangci.toml
  Makefile
  dialtesting/http_script.go
  dialtesting/http_script_test.go
  dialtesting/http_test.go
  dialtesting/icmp.go
  dialtesting/multi.go
  dialtesting/task.go
  dialtesting/tcp.go
  dialtesting/tcp_test.go
  dialtesting/websocket.go
  diskcache/diskcache.go
  diskcache/get.go
  diskcache/meta_test.go
  diskcache/put.go
  diskcache/put_test.go
  filter/eval.go
  point/decode.go
  point/encode.go
  point/encode_test.go
  point/encode_v2.go
  point/kvs.go
  point/kvs_test.go
  point/lp.go
  point/option.go
  point/pbpoint_test.go
  point/point.go
  point/ptpool.go
Labels: size/L
